version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_URL=http://localhost:5000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm start
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app/server
      - ./api:/app/api
    command: npm run dev
    restart: unless-stopped

  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=https://your-frontend-url.vercel.app
    restart: unless-stopped
    profiles:
      - production
