version: '3.8'

services:
  # Development services
  dev-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm start
    profiles:
      - dev

  dev-backend:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app/server
    profiles:
      - dev

  # Production service (simplified)
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=https://your-frontend-url.vercel.app
    restart: unless-stopped
    profiles:
      - production
